using System.Net;
using System.Text.Json;
using Supabase.Postgrest;
using FantasyProsScrape.Models.Supa;
using Client = Supabase.Client;

namespace FantasyProsScrape.Services.Repositories;

/// <summary>
/// Reads and writes <c>FantasyProsRankRuns</c>. See <see cref="IRunRepository"/>.
/// </summary>
public class RunRepository : IRunRepository
{
    /// <summary>Postgres' unique_violation SQLSTATE, as PostgREST echoes it in an error response body.</summary>
    private const string UniqueViolationSqlState = "23505";

    private readonly Client _supabase;
    private readonly IPostgrestRawWriter _rawWriter;
    private readonly ILogger<RunRepository> _logger;

    public RunRepository(Client supabase, IPostgrestRawWriter rawWriter, ILogger<RunRepository> logger)
    {
        _supabase = supabase;
        _rawWriter = rawWriter;
        _logger = logger;
    }

    public async Task<string?> GetLatestPayloadHashAsync(
        int season, int week, long positionId, string scoring, CancellationToken cancellationToken = default)
    {
        var response = await _supabase
            .From<FantasyProsRankRun>()
            .Select("payload_hash")
            .Filter("season", Constants.Operator.Equals, season)
            .Filter("week", Constants.Operator.Equals, week)
            // Postgrest's Filter(...) only accepts string/int/float/List/Dictionary/FullTextSearchConfig/Range
            // criterion types (not long) - cast down; position ids are always small (1-5).
            .Filter("position_id", Constants.Operator.Equals, (int)positionId)
            .Filter("scoring", Constants.Operator.Equals, scoring)
            .Order("fetched_at", Constants.Ordering.Descending)
            .Limit(1)
            .Get(cancellationToken);

        return response.Models.FirstOrDefault()?.PayloadHash;
    }

    /// <summary>
    /// Inserts via <see cref="IPostgrestRawWriter"/> rather than the typed client's
    /// <c>.Insert(...)</c>: that method serializes a literal <c>id: 0</c>, and because this column
    /// is <c>GENERATED BY DEFAULT AS IDENTITY</c> (not <c>GENERATED ALWAYS</c>) Postgres accepts the
    /// override instead of rejecting it - silently planting an <c>id = 0</c> row that every
    /// subsequent insert in the run then collides against. The payload built here omits <c>id</c>
    /// entirely so PostgREST always assigns a fresh one.
    /// </summary>
    public async Task<bool> InsertRunAsync(FantasyProsRankRun run, CancellationToken cancellationToken = default)
    {
        var payload = new[]
        {
            new
            {
                season = run.Season,
                week = run.Week,
                position_id = run.PositionId,
                scoring = run.Scoring,
                payload_hash = run.PayloadHash,
                payload = run.Payload,
                total_experts = run.TotalExperts,
                fp_last_updated = run.FpLastUpdated,
                fetched_at = run.FetchedAt
            }
        };

        var json = JsonSerializer.Serialize(payload);
        var response = await _rawWriter.PostAsync(
            "FantasyProsRankRuns", onConflict: null, json, "return=minimal", cancellationToken);

        if (response.StatusCode == HttpStatusCode.Conflict)
        {
            var body = await response.Content.ReadAsStringAsync(cancellationToken);
            if (IsUniqueViolation(body))
            {
                // Someone else's concurrent run already stored this exact (season, week, position_id,
                // scoring, payload_hash) - the unique constraint is the race backstop for the hash
                // check in GetLatestPayloadHashAsync. Not a failure.
                _logger.LogInformation(
                    "FantasyProsRankRuns row for {Season} wk{Week} pos {PositionId} {Scoring} hash {Hash} already stored by a concurrent run; skipping",
                    run.Season, run.Week, run.PositionId, run.Scoring, run.PayloadHash);
                return false;
            }
        }

        response.EnsureSuccessStatusCode();
        return true;
    }

    /// <summary>Whether a PostgREST error response body reports Postgres' unique_violation SQLSTATE.</summary>
    private static bool IsUniqueViolation(string responseBody)
    {
        try
        {
            using var doc = JsonDocument.Parse(responseBody);
            return doc.RootElement.TryGetProperty("code", out var code)
                && code.GetString() == UniqueViolationSqlState;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    public async Task<(int Season, int Week)?> GetMostRecentSeasonWeekAsync(CancellationToken cancellationToken = default)
    {
        var response = await _supabase
            .From<FantasyProsRankRun>()
            .Select("season,week")
            .Order("fetched_at", Constants.Ordering.Descending)
            .Limit(1)
            .Get(cancellationToken);

        var latest = response.Models.FirstOrDefault();
        return latest is null ? null : (latest.Season, latest.Week);
    }
}
