namespace FantasyProsScrape.Services;

/// <summary>
/// Raw PostgREST HTTP writer for tables whose primary key is an identity column
/// (<c>[PrimaryKey("id", false)]</c>). The Supabase.Postgrest typed client's <c>.Insert(List&lt;T&gt;, ...)</c>
/// and <c>.Upsert(List&lt;T&gt;, ...)</c> methods serialize a literal <c>id: 0</c> for every row regardless
/// of <c>shouldInsert: false</c>. Two or more brand-new rows in the same batch then collide on the
/// real primary key within a single INSERT, and on a <c>GENERATED BY DEFAULT AS IDENTITY</c> column
/// (which permits an explicit override) a single-row insert can silently plant a corrupted
/// <c>id = 0</c> row. Repositories writing such models build a JSON payload with no <c>id</c>
/// property at all and POST it here directly against the PostgREST table endpoint instead of going
/// through the typed client. See the <c>fantasy_calc_scrape</c> repo's
/// <c>SupabaseDatabaseService.UpsertFantasyCalcPlayerValuesAsync</c>, which established this pattern
/// for the same client limitation.
/// </summary>
public interface IPostgrestRawWriter
{
    /// <summary>
    /// POSTs <paramref name="jsonBody"/> (a JSON array of row objects with no <c>id</c> property) to
    /// <paramref name="table"/>. <paramref name="onConflict"/>, when non-null, adds
    /// <c>?on_conflict=...</c> so PostgREST performs an upsert instead of a plain insert; pair it
    /// with a <paramref name="prefer"/> that includes <c>resolution=merge-duplicates</c>.
    /// Does not throw on a non-success status - callers decide (e.g. <c>RunRepository</c> inspects a
    /// 409 response body for a uniqueness violation before deciding whether to surface it).
    /// </summary>
    Task<HttpResponseMessage> PostAsync(
        string table, string? onConflict, string jsonBody, string prefer, CancellationToken cancellationToken = default);
}
